### ISSUE TITLE
Release schedule, TODO list, open questions, future, RFC

### ISSUE THREAD

**Issue by dumblob** [named-data/NDN-packet-spec#3]
I'm new to NDN and after reading in an executive summary of the last report that few years ago the original programme was ended (i.e. there doesn't seem to be any consistent funding any more), I wonder whether there is any release schedule (or any other schedule or at least a list of TODO items and open questions).

Last tag in this repository with NDN specification (which I consider to be the main outcome of all the NDN initiative - hopefully some day an RFC) is already 4 years old but there are still some commits here and there in many NDN repositories.

Could you shed some more light on what is going on currently and in the future?

I'd be also very much interested in any commercial or federal/state activity building upon NDN (based on https://tools.ietf.org/html/rfc8793 one would say there is nothing available, but from how I know DARPA etc. it's not this easy).

**Comment by yoursunny** [comment]
> Last tag in this repository with NDN specification is already 4 years old but there are still some commits here and there in many NDN repositories.

The current NDN spec is version 0.3, but there's no tag because the protocol is always evolving. You should consider the latest commit in the default branch to be the current NDN protocol.
Notice that this repository only contains the network layer protocol. NDN also needs link layer and application layer protocols, which are listed on https://redmine.named-data.net/projects/ndn-tlv/wiki .

> NDN specification, which I consider to be the main outcome of all the NDN initiative - hopefully some day an RFC

@kmnichols is working on writing an RFC for the NDN network layer protocol. Maybe she can comment on the progress.

> I'd be also very much interested in any commercial or federal/state activity building upon NDN

See https://github.com/usnistgov/ndn-dpdk and https://yoursunny.com/p/2020/NDN-DPDK-ICN2020/
